### ISSUE TITLE
Is there a license for the data?

### ISSUE THREAD

**Issue by jfoz** [naptha/tessdata#2]

**Comment by jeromewu** [comment]
In face I don't know if there is any license issue for the data.
As we mirror the data from this repo: https://github.com/tesseract-ocr/tessdata
I would suggest you consult tesseract-ocr team.

**Comment by jfoz** [comment]
Thank you.

It seems like they use this license: https://github.com/tesseract-ocr/tessdata/blob/master/LICENSE
