### ISSUE TITLE
Document this page and the npm packages

### ISSUE THREAD

**Issue by MCMattia** [naptha/tessdata#6]
Hi,

I need to download the trained data to offer offline ocr to my users.

I saw the existence of this repo and that you had problems hosting big files on github so I guess that's why you created the npm packages for each language.

This is very good because now I can get the traineddata from jsdelivr with the urls:
https://cdn.jsdelivr.net/npm/@tesseract.js-data/deu/4.0.0_best_int/deu.traineddata.gz
https://cdn.jsdelivr.net/npm/@tesseract.js-data/eng/4.0.0_best_int/eng.traineddata.gz
https://cdn.jsdelivr.net/npm/@tesseract.js-data/ita/4.0.0_best_int/ita.traineddata.gz

I think this is also the default way tesseract.js V5 downloads the trained data.

Could you please write a short paragraph in the readme describing what you did with the npm packages and jsdelivr and how users can benefit from it?

Thank you!

**Comment by Balearica** [comment]
Thanks for the suggestion, I've added a more descriptive README that better documents this repo, the NPM packages, and the CDN options.
